# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish dagster-ibis-bigquery to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_NAME: dagster-ibis-bigquery

permissions:
  contents: 'write'
  id-token: 'write'


jobs:
  release-build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          ref:  ${{github.ref_name}}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Select package
        run: |-
          cd modules/${{ env.PACKAGE_NAME }}

      - name: Get version
        run: |-
          git fetch --tags --force
          echo "VERSION=$(uvx --from=dunamai dunamai from any --no-metadata --style pep440)" >> "$GITHUB_ENV"

      - name: Unit test
        run: |-
          uv sync --group=dev
          uv run pytest

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish ./dist/${{env.PACKAGE_NAME}}-${{env.VERSION}}* --token ${{secrets.UV_PUBLISH_TOKEN}}
