# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish dagster-ibis-duckdb to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_NAME: dagster_ibis_duckdb
  DIR_NAME: dagster-ibis-duckdb

permissions:
  contents: 'write'
  id-token: 'write'


jobs:
  release-build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          ref:  ${{github.ref_name}}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Get version
        working-directory: modules/${{ env.DIR_NAME }}
        run: |-
          echo "VERSION=$(uv version --short)" >> "$GITHUB_ENV"

      - name: Unit test
        run: |-
          uv sync --group=dev

      - name: Build
        run: |-
          uv build --package=${{env.PACKAGE_NAME}}

      - name: Publish
        run: |-
          uv publish ./dist/${{env.PACKAGE_NAME}}-${{env.VERSION}}* --token ${{secrets.UV_PUBLISH_TOKEN}}
